AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudWatch Alarm Template"

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: Test
      TopicName: TestforCloudwatch

  SNSubscription:
    Type: AWS::SNS::Subscription
    Properties: 
      TopicArn: !Ref SNSTopic
      Endpoint: test@xyz.com
      Protocol: email

  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: CPU alarm for my instance
      AlarmActions:
        - !Ref SNSTopic
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '3'
      Threshold: '90'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: InstanceId
        Value: i-05276ceaace8bddff

# Type: AWS::CloudWatch::Alarm
# Properties: 
#   # ActionsEnabled: Boolean
#   # AlarmActions: 
#   #   - String
#   # AlarmDescription: String
#   # AlarmName: String
#   ComparisonOperator: String
#   # DatapointsToAlarm: Integer
#   Dimensions: 
#     - Dimension
#   # EvaluateLowSampleCountPercentile: String
#   EvaluationPeriods: Integer
#   # ExtendedStatistic: String
#   # InsufficientDataActions:  // for INSUFFICIENT STATE
#   #   - String
#   MetricName: String
#   #Metrics: 
#   #  - MetricDataQuery
#   Namespace: String
#   OKActions: 
#     - String
#   Period: Integer
#   Statistic: String
#   Threshold: Double
#   ThresholdMetricId: String
#   TreatMissingData: String
#   Unit: String
